SetEnv IMU_QUATERNION_FILE /var/www/html/imu-data/imu_quaternion.txt
<Directory /var/www/html>
    Options +ExecCGI
    AddHandler cgi-script .cgi .py
</Directory>
<Files "imu_quaternion.cgi">
    SetHandler cgi-script
</Files>
